### ISSUE TITLE
Package Receipt not being written to the system

### ISSUE THREAD

**Issue by jolegape** [freegeek-pdx/mkuser#4]
Hi There,

I am creating several user packages, which when installed on the destination device create the user accounts, with the correct settings as expected. The issue I am seeing, is that receipts for the PKG files are not being created, which means I cannot use Munki to deploy them as part of the initial build. Is this expected or a bug I have encountered?

I am using `mkuser --username smc_exam --uid 503 --password Sup3rS3cr3tPa55w0rd --hidden --pkg` to generate the pkg. The smc_exam account is listed in the directory utility, however `pkgutil --pkgs` does not list the receipt mkuser.pkg.smc_exam. I also tried by appending `--pkg-id  au.edu.qld.stmonicas.smc_exam` as the package id when creating the pkg.

This isn't a huge issue, as rather than deploy via Munki I can modify my workflow to deploy it another way, or use a different detection method potentially. Just wanted to raise this in case it is indeed a bug.

Thanks

Gavin

**Comment by PicoMitchell** [comment]
Thanks for taking the time to report this.

But, this is indeed the intended behavior and is mentioned in the `--package` help info: https://github.com/freegeek-pdx/mkuser#--package-path---pkg-path---package---pkg--folder-path--pkg-file-path--no-parameter-working-directory-

> The distribution package (product archive) created will be suitable for use with `startosinstall --installpackage` or `installer -pkg` or "Installer" app, **and is also "no payload" which only runs scripts and leaves no receipt.**

If you are just wanting to detect that the `mkuser` process was fully completed successfully via package, you could check the "/var/log/install.log" file for the "postinstall: mkuser: Successfully created" lines. Those lines will contain the user type and username, so they will be unique for each user and you could automate that check with `grep` in a script if you wanted to after manually checking a successful install for the exact line contents to `grep` for (I would not recommend matching the entire line that includes the number of verifications as that number may change in future versions, just `grep` through to the end of the username which I do not plan on ever changing for that log line).

If there is ever an error, those will be listed in the "install.log" file as well and that success line will not be written.

I don't use Munki myself, does it rely on package receipts to know if the package has already been installed or something?

I personally like that the "no payload" package does not leave a receipt since it means it leaves no "unnecessary" traces other than the user (and the log). `mkuser` can also be run directly without creating a package which would not leave a receipt anyways, so I also liked that consistency between the different user creation methods.

**Comment by jolegape** [comment]
My apologies. I completely missed that bit when I was reading the docs. 

Munki can use package receipts. It can also use other scripting methods to detect whether packages are required / applicable or not. I will use a script to detect whether the user account exists or not for now, before eventually moving it out of Munki into part of the OS deployment.

Thanks for pointing out the error of my ways! :)

**Comment by PicoMitchell** [comment]
Checking that the user account exists should be fine most of the time, but keep in mind that there are things that happen after the initial user creation (depending on the options specified) that could also fail (but shouldn't). So, it isn't impossible for the user account to exist, but some later part of the `mkuser` process had an issue (but again, errors shouldn't generally happen at all, just pointing it out in the interest of knowing how things in `mkuser` work).
