### ISSUE TITLE
Feature Request: option to check against local accounts only

### ISSUE THREAD

**Issue by wakco** [freegeek-pdx/mkuser#7]
Discovered due to an obvious conflict that mkuser was unable to create account where matching network accounts were available.

Traced this down to the use of `dscl /Search`, which after a Mac is bound to AD, also checks network accounts.

To resolve this issue in my case, I simply replaced all `dscl /Search`'s with `dscl /Local/Default` in the script. However, I'd like to request that it be an option to be able to choose between local only or network wide checking.

**Comment by PicoMitchell** [comment]
When `mkuser` checks `dscl /Search` vs `dscl .` (aka `dscl /Local/Default`)  was decided carefully and intentionally.

I was intentionally not ever wanting `mkuser` to be able to create a duplicate/conflicting user even if that conflicting user in an AD account.

What is the scenario where you would want a local account that conflicts with an AD account? And what types of conflicts would you want to be allowed (full username, short username, uid, etc)?

The main reason I wanted to avoid this is that I don't fully understand the repercussions of allowing something like this and I do not have an environment where I could test these scenarios myself.

**Comment by wakco** [comment]
My best example is having a local only open day guest account, where for other purposes there is also an AD open day account.

I am aware there are some potential conflicts, but a Mac will default to a local account over an AD account, where the userid is different, which in turn means the AD account is blocked.

**Comment by PicoMitchell** [comment]
I'll consider adding another options to only check for conflicts against local accounts. Definitely would want that to be an explicit option rather than the default behavior though in case someone doesn't realize they could block an AD account.

I think this should likely only apply to usernames though, right? Seems like allowing a conflicting UID of an existing AD account would be bad news.

And are you referring to a conflicting short account name or full account name?

How would home folders come into this? Seems like allowing two different accounts with different UIDs would be problematic too since one of those users wouldn't own the home folder.

**Comment by wakco** [comment]
in my testing, username (short name), and full account name. Home folders must be local only as well, when using this option.

As for the UID, I'd go so far as to limit the UID to no larger than 1024 (or whatever that mark is between local and network UIDs). Or not allow UID selection, requiring automatic UID creation only.

**Comment by PicoMitchell** [comment]
If I add this, I'm thinking UID and GUID etc (and other group checks) would still be checked against AD accounts for conflicts, so that logic wouldn't need to change (I don't think).

So only the short and full user names would be allowed to conflict with AD accounts.

But I'm still a bit unclear on how the home folders would work. Does your AD account have a different home folder path than the local account?

It seems like it would make sense that the new local account would still need to check for and not allow home folder paths that exists already for AD accounts. But there may be things going on there that I don't understand.

I'm also considering that this may be such a niche thing that it may make more sense to be a manual variable change in the source code rather than a new option, which I think might confuse some situations if folks don't understand exactly what behavior it's changing.

**Comment by wakco** [comment]
Oh, sorry, I mis-read your home folder path reference, yes if the home folder path already exists, then yes it should still fail, due to the obvious conflict.

And also yes, I agree, a variable in the script over an option does sound like a better idea, as someone like me that is capable of editing the script, is much more likely to understand the implications than the average person.

**Comment by PicoMitchell** [comment]
I'm thinking it would really just be _optionally_ changing the `dscl /Search` check in this specific section to `dscl .`: https://github.com/freegeek-pdx/mkuser/blob/main/mkuser.sh#L4646-L4679

I don't think changing any of the other UID/GUID/group/home folder checks would be necessary or safe in all situations, and a primary goal of `mkuser` is really to be extra safe and not allow any conflicts and verify everything.

**Comment by PicoMitchell** [comment]
I plan on getting back into some other `mkuser` updates next week. Can't give a deadline on when the next update will be out, but I think I'll be able to able to incorporate this as an internal source variable option that would need to be edited manually. I'll have some code comments around that variable, but doing it that was also saves me a lot of time/energy that adding a new option with help info would require.

**Comment by PicoMitchell** [comment]
Maybe I could make an undocumented option that would be a normal CLI option, but I would just not write help info for it. We'll see how it comes together when I get back into the code.

**Comment by PicoMitchell** [comment]
`mkuser` Version 2023.3.15-1 has just been released which includes a new (undocumented) `--only-check-locally-for-conflicting-names` option which will only check the user account name and full name for conflicting existing _local_ users and _not AD_ users.
